import Header from '@/companents/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/companents/footer/Footer'
import Menu from '@/companents/LeftMenu/Menu'
import Calender from '@/companents/Calender/Calender'
import CalenderNotes from '@/companents/Calender/CalenderNotes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-[95%] mx-auto">
        
        <div className='flex justify-between'>
          
          <div className='w-[10%]  h-screen '>
            <Menu />
          </div>
          
          <div className='w-[65%] bg-slate-100 '>
            <Header />
            {children}
            <Footer />
          </div>
          <div className='w-[25%] h-screen '>
            <Calender />
            <CalenderNotes />
          </div>
        </div>
       
      </body>
    </html>
  )
}
